### ISSUE TITLE
Matter Overdrive console spam (again)

### ISSUE THREAD

**Issue by LacSappy** [Beyond-Reality/Beyond-Reality-Divergence#240] opened 2015-10-29 15:04 UTC
The Matter Entry problem is back (Beyond Reality: Divergence v1.2.7) SMP

16:00:58 CONSOLE: [Matter Overdrive]: There was a problem getting a Matter Entry.
16:00:58 CONSOLE: [Matter Overdrive]: There was a problem getting a Matter Entry.
16:00:58 CONSOLE: [Matter Overdrive]: There was a problem getting a Matter Entry.
16:00:58 CONSOLE: [Matter Overdrive]: There was a problem getting a Matter Entry.
16:00:59 CONSOLE: [Matter Overdrive]: There was a problem getting a Matter Entry.

I just updated my server from 1.2.6.3 to 1.2.7. 

This is my second post on github and I really don't know if this is the right section to post it or not.

**Comment by Dominance** [comment] 2015-10-29 20:40
Does it eventually stop? From my testing this version when I turned it back on there was some initial spam when creating the registry file. But once created the spam goes away. There is still a on going open issue on there issue tracker btw.

**Comment by Dradgit** [comment] 2015-11-04 21:00
I tried to create a new server instance of this pack from the ATLauncher on the latest beta version 1.2.7.1, and got the same issue. I didn't want a giant log file clogging my desktop's SSD so I tried on my laptop. After waiting for approx 20 minutes I had a log file about 300 MB large with this error spammed a few million times.

[14:32:35] [pool-4-thread-1/ERROR] [Matter Overdrive/mo]: There was a problem getting a Matter Entry.
java.lang.NullPointerException
    at net.minecraft.item.ItemStack.func_77960_j(ItemStack.java:217) ~[add.class:?]
    at matteroverdrive.handler.MatterRegistry.getOreDicionaryEntry(MatterRegistry.java:333) ~[MatterRegistry.class:?]
    at matteroverdrive.handler.MatterRegistry.getEntry(MatterRegistry.java:294) [MatterRegistry.class:?]
    at matteroverdrive.handler.MatterRegistry.getMatterFromList(MatterRegistry.java:467) [MatterRegistry.class:?]
    at matteroverdrive.handler.MatterRegistry.getMatterFromRecipe(MatterRegistry.java:372) [MatterRegistry.class:?]
    at matteroverdrive.handler.thread.RegisterItemsFromRecipes.run(RegisterItemsFromRecipes.java:82) [RegisterItemsFromRecipes.class:?]
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_45]
    at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_45]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_45]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_45]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_45]

After the spamming stopped it did say it saved the mod registry, so I'm guessing you're right about what the issue is. Still, even if it's not happening after the first startup that's an insane amount of spam. The matter overdrive mod needs handles for mod items with missing names apparently.

**Comment by charlotteroose** [comment] 2015-12-12 21:06
I'm also getting the above error. It spammed 2mil lines into my console before I force stopped my server. Is there a solution yet? Would a copy of the logs be of use to you?

**Comment by ajthemacboy** [comment] 2016-01-02 19:47
I have this too, it spammed until the calculations were done. Even if the bug is only temporary it's a polishing issue and should be fixed.

**Comment by Buuz135** [comment] 2016-04-28 14:02
Fixed? I don't get the spam in 1.2.9 in a new world. Reply if you still have it 1.2.9

**Closed as completed by Buuz135** 2016-04-28 14:02 UTC
Labels: Need More Info
