### ISSUE TITLE
Singleplayer resets to main menu when loading.

### ISSUE THREAD

**Issue by DrDerpy16** [Beyond-Reality/Beyond-Reality-Divergence#324] opened 2016-04-23 19:36 UTC
I cleared the logs and tried again
Upload: http://paste.atlauncher.com/view/d082e63f

**Comment by vagaprime** [comment] 2016-04-23 21:07
dupe of https://github.com/Beyond-Reality/Beyond-Reality-Divergence/issues/320

**Comment by SkuxxDeluxe** [comment] 2016-04-24 01:46
As with #320 , disable not enough resources.

**Comment by Buuz135** [comment] 2016-04-24 12:55
FIXED IN 1.2.9

**Closed as completed by Buuz135** 2016-04-24 12:55 UTC
