### ISSUE TITLE
Journeymap getting partially reset on game load

### ISSUE THREAD

**Issue by mrbaggins** [Beyond-Reality/Beyond-Reality-Divergence#99] opened 2015-09-22 23:37 UTC
Since the 1.2.2 updates, whenever I load my game, the rectangular area of 32x32 chunks around where I load in gets wiped in Journeymap. The circular area covered by what I am near gets loaded back in, simply because I'm near it, but I end up with a giant rectangle of unexplored terrain every time I load up.

![Screenshot](http://i.snag.gy/XCoG7.jpg)

The land is not being reset, it's maintaining changes. Note the iron? / gold / nickel waypoints in the middle of the space, that area remains mined / affected by my changes. 

I know Journeymap is an optional mod, but it's one specifically listed as such.

**Comment by Dominance** [comment] 2015-09-23 00:06
I have not a clue what would be causing this. Being a optional mod does not mean it is unsupported. Just means its client side with Beyond Reality packs for the most part. As for fixing it? I have not a clue how it could be fixed on my end.

**Comment by b0bst3r** [comment] 2015-09-23 01:09
Doesn't really help any but - http://pastebin.com/5AxPVs0K

Happening on your server too Dom and yeah it's all clientside

**Comment by b0bst3r** [comment] 2015-09-23 01:11
Actually it maybe something to do with world gen changes between versions, be interesting to see if this still occurs when we reset next big update.

**Comment by Dominance** [comment] 2015-09-23 02:06
If anyone figures out the root cause to this let me know. I will try and figure it out in the mean time.

**Comment by b0bst3r** [comment] 2015-09-23 02:41
I've just spotted another post on reddit with this exact same issue not sure it's related to your pack.

**Comment by Dominance** [comment] 2015-09-24 00:12
Ok closing yeah I seen that exact same thing. Even happens on some other packs I tested as well

**Closed as completed by Dominance** 2015-09-24 00:12 UTC
Labels: help wanted, invalid
