### ISSUE TITLE
1.2.8 many issues

### ISSUE THREAD

**Issue by choum33** [Beyond-Reality/Beyond-Reality-Divergence#306] opened 2016-02-27 14:10 UTC
Hello,

1) I'm able to start my divergence server on my computer but the client crash when i try to connect it.
2) serveur stop if i try to start it on my cloud server with progression error. 
http://pastebin.com/kzVSTByE
No crashlog is generated in this case...

3) i know it's not supported but it's for info, i can't start the server with Kcauldron nor locally nor in cloud. I tryed 4 versions of kcauldron and forge with same result.

My best regards

**Comment by Dominance** [comment] 2016-02-27 16:42
Strange as it's a progression error of which I did not update. Try to delete your progression configs and use your back
Hello,

1) I'm able to start my divergence server on my computer but the client crash when i try to connect it.
2) serveur stop if i try to start it on my cloud server with progression error.
http://pastebin.com/kzVSTByE
No crashlog is generated in this case...

3) i know it's not supported but it's for info, i can't start the server with Kcauldron nor locally nor in cloud. I tryed 4 versions of kcauldron and forge with same result.

My best regards

---

Reply to this email directly or view it on GitHub:
https://github.com/Beyond-Reality/Beyond-Reality-Divergence/issues/306

**Comment by vagaprime** [comment] 2016-02-28 02:44
Following the title of this issues I will use it to report other problems and Issues

the first is normal ores spawning https://github.com/Beyond-Reality/Beyond-Reality-Divergence/issues/307  _**Fixed**_

The Furnace is also locked behind Magneticraft, Hexcraft, and SF artifacts. _**Fixed**_

The forestry House is spawning in villages.

The normal mana pool, spreader, and tablet are not locked to anything (Not sure if that is intended.) _**Intended, you cant get them anyway**_

The framed drawers form Storage drawers are not locked. _**Fixed**_

The SF Artifacts quest is also showing an Invalid item as a quest reward.

That is all I have found so far.

**Comment by Dominance** [comment] 2016-02-28 19:32
Will get to it asap.

**Comment by vagaprime** [comment] 2016-02-29 01:48
Will we also be getting the newest update of Armour's Workshop?

**Comment by Dominance** [comment] 2016-02-29 01:50
I will get it updated again and tackle these issue tomorrow

**Comment by Boninsky** [comment] 2016-03-03 19:19
Hey there,
started playing Divergence on Single Player. Nice Pack but now i have some trouble...
Wanted to open a Loot Bag and then game crashed to Desktop. From that point i cant join back to this world. Made a new one and after a while it also crashed when placing Oak Fence. It sucks a bit to always create a new World. Dont know whats causing the crash.
Only wanted to let you know about that...
Will try again and give it more Testing...

**Comment by vagaprime** [comment] 2016-03-04 00:14
Boninsky. We would be able to help you out more if we could get a copy of your crash logs.

**Comment by Boninsky** [comment] 2016-03-04 14:33
this is the last crash reports...

https://www.dropbox.com/sh/6d28pb6b99mqgmy/AAAFqBjzkR4oBv5zjuqdLtdTa?dl=0

Hope you will have access to the reports with that. 
If it does not work, let me know...idk what else i can do to send you the reports.
Biut thx for helping...

**Comment by Boninsky** [comment] 2016-03-04 17:32
OK, i think i will wright down some more issues if i find some...maybe there is some ideas to give the pack a better gameplay...Hope its ok for you :)
its possible to place blocks in the temple but as a mistake i placed a block directly behind an opened door of a quest room. now its protected from the invisible door block so i cant break it and cant get into the room to get the loot and unlock this quest...
also would be nice to get rid of the loot skeleton from dying when nothing is inside. it shows hp but cant break it or something.

**Comment by Dominance** [comment] 2016-03-04 17:51
Somethings you just have to accept as a fact that they will never be fixed. Such as the block behind the door issue. There is no viable way to accomplish a fix for this. Other things like the loot skeletons will just have to be removed. They are on there last leg on being stripped to almost nothing as is. Largley due to chromaticraft's towers not getting along with them and tinkers tools multiplying issues.

**Comment by vagaprime** [comment] 2016-03-04 18:40
Boninsky it's looking like the problem is dealing with Binne core and Dragon api not playing nice. This could be due to the binne patcher mod. I as about to open a ticket with binne fixes. Mind if I link you crash logs along with mine?

**Comment by Boninsky** [comment] 2016-03-04 18:54
Thats ok Vagaprime...

**Comment by vagaprime** [comment] 2016-03-04 22:48
Just heard back from the author of Binnie Patcher. The fence crash is fixed we just need to update to 1.6

https://github.com/Chocohead/Binnie-Patcher/issues/7#issuecomment-192465830

**Comment by tapayton83** [comment] 2016-04-18 04:20
It is not a crash, and I may just not know which button to press, but whenever I use one of the chairs to unlock the next progression, I get stuck in the chair and have to quit minecraft and re open to get unstuck.

**Comment by vagaprime** [comment] 2016-04-18 06:23
same key you use to dismount a horse, minecart, or boat

**Comment by vagaprime** [comment] 2016-04-18 06:28
more issues with the 1.2.8

https://github.com/Beyond-Reality/Beyond-Reality-Divergence/issues/321

https://github.com/Beyond-Reality/Beyond-Reality-Divergence/issues/315

https://github.com/Beyond-Reality/Beyond-Reality-Divergence/issues/312

**Comment by Dominance** [comment] 2016-06-28 14:02
okie dokie It looks like via updating I got all of these remaining issues fixed from what I can tell.

**Closed as completed** 2016-06-30 15:38 UTC
Labels: Fixed Next Version
