### ISSUE TITLE
Bug after completing the loading

### ISSUE THREAD

**Issue by Ethern8ai** [Beyond-Reality/Beyond-Reality-Divergence#319] opened 2016-04-11 03:08 UTC
Hi, my Divergence pack wont work on MultiMC (version: 0.4.11-751) or offline

It does loads totally then before showing the starting screen crashes...

crash report: http://pastebin.com/xgVK9ygw

i tryed to test few forge versions and few others desperate attempts but i cant find out were is the problem..

And any idea why when im offline half of the packs i have wont work? most of the time MultiMC says minecraft crashed with error code -1 and Exception in thread "AE2 VersionChecker"

thanx H.A.N.D.

**Comment by vagaprime** [comment] 2016-04-11 03:36
Ok so the problem is not with AE2 version checker. Its with a different set of mods. The mods you want to remove are listed in this issue

https://github.com/Beyond-Reality/Beyond-Reality-Divergence/issues/315

Dom if you are getting theses issues. Any chance we can get an update pushed that at least has these mods removed?

**Comment by Buuz135** [comment] 2016-04-24 12:55
FIXED IN 1.2.9

**Closed as completed by Buuz135** 2016-04-24 12:55 UTC
