### ISSUE TITLE
[ISSUE] Massive FPS lag in Chromaticraft structures and The Temple.

### ISSUE THREAD

**Issue by hron84** [Beyond-Reality/Beyond-Reality-Divergence#31] opened 2015-09-06 03:18 UTC
I experience massive FPS drop near any Chromaticraft structure (approx 60-100 block radius) and also inside the temple with the latest pack. While Chroma structures can be avoided, the Temple is not. Please fix one or both of them.

**Comment by Dominance** [comment] 2015-09-06 04:07
Not really sure what I could possibly do with the pylons. As for the temple, Are you using the resource pack BR assets? If so try to disable that to set the default textures to 16bit instead of 64. The only thing I could think of that would limit your FPS would be ether textures or carpenters blocks.

**Comment by hron84** [comment] 2015-09-06 07:19
@Dominance yes, I use BR assets. I'll try it out anyway. Btw, could you please make these assets available as 16x16 too? I think there's quite much user with low-end graphics card and they'd really appreciate it.

Also I don't think Carpenters block can cause a problem, since I use a dozen of them in my bases in other modpacks and nothing goes wrong.

About pylons: could you make them _more_ rare? Perhaps one within 1000-1500 block? I used same seed as BevoLJ in his let's play ("Divergence LP") and I have 3-4 pylon in a relative small area. As I have to go far from them they tightens the "habitable" areas. Note: I did not consider how affects this the progression in the modpack as I did not reached that tech level.

**Comment by Dominance** [comment] 2015-09-06 08:00
Unfortunately there is no config options available to me to set the rarity of the ChromatiCraft pylons. The only one available to my knowledge is the range of which it can attack you. That has already been cut by more than half. As for the 16x16 bit assets. The divergence resource pack just overwrites the default 16x16 textures with 64x64. If you disable BR- assets you essentially will be using the 16x16 version. 

If disabling the BRassets resource pack does not help. and if you do figure out what is causing the FPS drop in the temple. Please let me know and I will address it asap. I will keep looking on my end how ever its hard to pin point it as I do not have fps issues inside the temple myself.

**Comment by hron84** [comment] 2015-09-06 08:18
I tried out without BR assets, and much better - even if still not perfect. The overall FPS for me is around 8-12 FPS (this provides a relative smooth moving for me), this falls to 5-7 in the temple (with hiccups), but previously it was about 4-6 FPS (with tendency to lower FPS, it was absolute unusable). Still not considering to make a base inside the temple (it would be an obvious choice otherwise) but I can live with it if Temple is only for progression - I waypointed it and forget until the next quest point.

**Comment by hron84** [comment] 2015-09-06 08:22
About required optimizations: I am not too good in debugging performance/FPS issues in MC, however that flowing redstone in the big reactor/tank is not helps. Also I'd check if the mod that causes strange transparency hiccups can be safely removed. MC is not too good in calculating these eyecandys if it's left alone however not every MC gamer uses high-end graphics card to the game.

**Comment by hmbigburt** [comment] 2015-09-06 11:03
i hate to butt in but i dont have any problems like this and i only have on board graphics card on my laptop

**Comment by Dominance** [comment] 2015-09-06 15:19
The transparency issue has been haunting me for the better part of a month. As of right now I have yet to pin point it. Happens for everyone how ever it is very random. So by pulling a mod and reloading you think ok I finally found it! then a hour later it pops up again. For now the best I can say is use f3+T this will reload everything and do away with it for a while.

**Comment by dilbert542** [comment] 2015-09-07 01:56
I have been also getting the lag around the temple. I am going to allocate more ram to to java to see if it helps i have 8 gigs a and a nvidia 610 card with 2gigs on that not sure why i am getting the lag

**Comment by hron84** [comment] 2015-09-07 06:27
@hmbigburt I playing with a discrete laptop card, NVidia GeForce 820M, but I exeriencing this issue. However, I'm pretty sure it's not about my card since I play with a many other modpacks and I do not get FPS lag from anything. I considering to try it out in a server environment too, since my laptop has a limited CPU capabilities, but I'm just unsure what can I do. The only thing I can blame for the lag is the BeyondRealityCore, since in the temple this is the only mod that I never met before, so it's a best target to blame anything. All other mods (including CraftHeraldy) appeared in another modpack.

**Comment by hmbigburt** [comment] 2015-09-07 18:09
damn youre laptop has a much better graphics card mine isn't that good lol, sorry if it sounded like i was trying to say the problem is on you're end didn't mean it like that.

**Comment by Dominance** [comment] 2015-09-08 12:26
Other than turning off the BRassets resource pack. The temple is made up of default blocks that are much like bedrock without the particle effects. So nothing there that should effect performance. The chairs them self may be the cause and I will look into profiling the temple asap.

**Comment by ReikaKalseki** [comment] 2015-09-12 06:16
@hron84

> About pylons: could you make them more rare? Perhaps one within 1000-1500 block?

You will want the exact opposite as soon as you need them.

**Comment by hron84** [comment] 2015-09-13 00:08
@ReikaKalseki it depends on. As the pylons causes FPS drops for me (a lot), it demotivates me to dive into ChromaticCraft too deep. I really love the dye trees and crystals with effect - but that's not enough balance to FPS drop.

Btw, the seed I currently use generates a quite much pylon - one within few hundred blocks. If the questline does not stricly require using them, with mid-game items I will can fly around to search them.

**Comment by hron84** [comment] 2015-09-13 00:11
@Dominance after several updates I went to the temple again, and it's better now. I do not made measurement yet (i just picked up the quest reward quickly) but it was a more smooth experience than before.

**Comment by hron84** [comment] 2015-09-13 00:12
@Dominance about pylons: I did not managed to try out them without HUD effect, but I will do tomorrow.

**Comment by ReikaKalseki** [comment] 2015-09-13 00:25
> If the questline does not stricly require using them

CC is impossible without them.

**Comment by hron84** [comment] 2015-09-13 07:42
@ReikaKalseki I meant Dominance questline

**Comment by Dominance** [comment] 2015-09-13 15:07
Yeah the quest he is referring to in divergence http://i.imgur.com/gVGtmOl.png Just locks the casting table and wand until you complete the quest. Then the entire mod is open to you. While you can still do some things without completing the quest. Its just part of the overall theme of the pack.

**Comment by hron84** [comment] 2015-09-13 16:28
Ahh, now I see.  If this is the case, I will consider to dive into CC but... only for the shake of the quest. Don't get me wrong, I like the structures and stuff it has, just... the first impression was not good, also these pretty structures are killed me few times, so... forgive me if I'm not too excited about this possibility. :smile:

**Comment by Dominance** [comment] 2015-09-14 05:18
@hron84 I have played minecraft for a while and trust me when I say it is one of the most amazing mods I have messed around with in my days. Reika Out did himself with it for sure.

**Comment by hron84** [comment] 2015-09-14 06:48
Hmm... maybe - just maybe - I'll give a second chance now for peaceful pylons :smile:

**Comment by Dominance** [comment] 2015-09-18 21:39
going to be remaking the temple in a future version. It will of course work with existing worlds. Ill just add a item to generate it on use. Closing for now.

**Closed as completed by Dominance** 2015-09-18 21:39 UTC
Labels: question, Next Version
