### ISSUE TITLE
Crash after mining a few ore

### ISSUE THREAD

**Issue by Hazdrubal** [Beyond-Reality/Beyond-Reality-Divergence#110] opened 2015-09-25 17:58 UTC
After mining a few blocks of nickle ore, I crash.

http://pastebin.com/J0NDydCB

**Comment by Dominance** [comment] 2015-09-25 18:18
This is one of thoughts no real way to tell why it crashed logs. the only way I would have a chance to figure it out is if I had both the client FML and server FML log both corresponding to the exact time this happened.

**Comment by Githubaccountlol** [comment] 2015-09-26 09:57
Happening to me too. Happens again every time I try to connect.

**Comment by helkarakse** [comment] 2015-09-26 10:10
Server side log: http://pastebin.com/5pEFqSeN, Server side FML Log: http://pastebin.com/sxT324CL for the above comment.

**Comment by Githubaccountlol** [comment] 2015-09-26 10:35
I don't have the FML for the actual first occurrence anymore, but this is from the most recent connection.  Same attempt as the one helk posted.

http://pastebin.com/XDmj1Xh8

**Comment by Dominance** [comment] 2015-09-27 23:44
I wish I could help just not really seeing anything beyond Netty issues / multiplayer issues. The root cause to this issue is beyond me. Maybe @pauljoda can give it a peek and find out.

**Comment by Dominance** [comment] 2015-09-30 18:07
Spent hours trying to figure this one out to no avail closing for now as it is a rare occurrence it seems.

**Closed as completed by Dominance** 2015-09-30 18:07 UTC
Labels: bug

**Comment by Githubaccountlol** [comment] 2015-10-04 23:32
Happened again, got the log from the first occurance this time.  Doesn't look helpful.
Lots of chromaticcraft pylons in the vicinity.

http://pastebin.com/Y3bweHQ6
