### ISSUE TITLE
Keep running out of RAM

### ISSUE THREAD

**Issue by Rake2244** [Beyond-Reality/Beyond-Reality-Divergence#39] opened 2015-09-08 20:10 UTC
I usually can't play for more than an hour, if that, before running out of ram and continually locking up.  It seems to happen even quicker if I'm travelling, especially by horse or boat.  I'm running 8gb of ram with 3gb given to mc.  I'm running the latest version of java 8 as well.  Any suggestions?

**Comment by Dominance** [comment] 2015-09-08 20:25
Id suggest giving it 4 which is the recommended amount and also the max amount. Generating a world can be depending on the chunk pretty intensive due to how ore gen works. You can also try to edit the harderunderground.cfg this section here

# Replaces vanilla stone with a stone that does not float and requires support.

```
# Drops unstable cobble which smelts into unstable stone.
# There is a crafting recipe to convert to vanilla.
#  [default: true]
B:replaceStone=true <-- Change that to false. It will disable the physics system in new chunks.
```

**Comment by Timefactor** [comment] 2015-09-08 20:32
I'm running into the same issue after an hour or so, the server just stops, no errors, no crash reports. I have a 4GB Creeperhost server with only this modpack running. I'm using 1.1.9.2.

I'll keep investigating on my end and report what I find.

**Comment by Dominance** [comment] 2015-09-08 23:47
Thanks let me know.

**Comment by Dominance** [comment] 2015-09-09 03:46
I am searching for mem leaks as I have encountered this issue as well by flying aimlessly around testing something. If you find the cause before you see a solution posted please let me know.

**Comment by Rake2244** [comment] 2015-09-09 13:47
It seems to be running a bit better with the extra ram, though I still do have slowdowns here and there, possibly tied to the falling stone.

**Comment by Timefactor** [comment] 2015-09-09 15:26
Will do. I've done some tweaking on my Creeperhost server and have it configured to optimize memory usage. I've also disabled the physics using replaceStone=false in the Harderunderground.cfg file.

It's been up for over 12 hours now, which is a first. But with 4GB's dedicated to it.. I only have 500MB's left free and declining. So my guess is that I wouldn't be able to leave it run for 24hours as it would exceed it's memory cap by then.

Java argument used below. Some of it may be Creeperhost specific but I figured it could be useful to someone :)

java -d64 -server -Xms32M -Xmx3978M -XX:+CMSIncrementalPacing -XX:+CMSClassUnloadingEnabled -XX:ParallelGCThreads=3 -XX:MinHeapFreeRatio=5 -XX:MaxHeapFreeRatio=10 -jar forge-1.7.10-10.13.4.1492-1.7.10-universal.jar nogui

**Comment by Dominance** [comment] 2015-09-10 04:41
Yeah sometimes falling stone can cause major slow downs here and there. Closing for now as there is another issue similar If you have any other issues reguarding FPS issue please post there.

**Comment by Dominance** [comment] 2015-09-10 06:57
ok figured out a major issue reopening. Please try this on your existing world. Find the file http://i.imgur.com/8F61Myu.png CustomOreGen_Options.txt It will be nested in your instance folder / saves / yourworld / DIM0 I need you to change the line deferredPopulationRange=0.0 to 16.0 like so http://i.imgur.com/k5sKQY4.png . Now go out and look for a new chunk and generally run around and let me know if it helps.

**Comment by Timefactor** [comment] 2015-09-10 13:57
I've made the changes. I'll test it out when I get home and let you know :)

**Comment by Timefactor** [comment] 2015-09-11 03:18
Server has been stable all day :) Looks good :)

**Comment by Timefactor** [comment] 2015-09-11 11:37
I spoke too soon. lol. It went down during the night, same symptoms, no crash-report. Although I did turn on the physics again. Turning it back off now.

**Comment by Dominance** [comment] 2015-09-12 16:41
ok well should be fixed up in next version a bit more

**Closed as completed by Dominance** 2015-09-12 16:41 UTC
